file:
  directory: C:/temp/playlist.txt

spring:
  application:
    name: mp3Tagger
  jackson:
    serialization.indent_output: true
  data:
    mongodb:
      database: OwnedMusic
      uri: mongodb+srv://devUser:fakePass1@cluster0.q2ny9rm.mongodb.net/?retryWrites=true&w=majority
  batch:
      job:
        enabled: false
server:
    port: 8089